### ISSUE TITLE
sodium version mismatch error

### ISSUE THREAD

**Issue by mixmix** [mmckegg/ferment#1]
# [EDIT] : solution :white_check_mark:  
 ```
npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source
 ```

---

# Bug

I've seen this before on patch* , can't recall solution.
Lets post a solution to this common bug here

```bash
> ferment@0.0.3 start /home/mix/projects/ferment
> electron index.js

error loading sodium bindings: Module version mismatch. Expected 50, got 48.
falling back to javascript version.
App threw an error during load
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/mix/projects/ferment/node_modules/bindings/bindings.js:76:44)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/mix/projects/ferment/node_modules/bindings/bindings.js:76:44)

```

**Comment by mixmix** [comment]
What I've tried : 
- local install
  - `npm install`, `npm run rebuild`
- global install

node `v6.2.1`
npm `3.10.6`

**Comment by ungoldman** [comment]
Getting the same issue. Tried updgrading to latest stable node (6.7), also tried deleting `ferment/node_modules` and reinstalling. No fix yet.

```
~ $ ferment
error loading sodium bindings: Module version mismatch. Expected 50, got 48.
falling back to javascript version.
App threw an error during load
Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/ngoldman/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/bindings/bindings.js:76:44)
```

**Comment by ahdinosaur** [comment]
same here, `node@6.2.1`.

**Comment by ungoldman** [comment]
Tried `npm run rebuild`, no dice.

**Comment by ahdinosaur** [comment]
so seems there's a bug in [`scripts/rebuild.js`](https://github.com/mmckegg/ferment/blob/master/scripts/rebuild.js). as i recall from a conversation with @mmckegg, this script only exists because it's not possible to use the standard [`electron-rebuild`](https://github.com/electron/electron-rebuild) due to [`sodium-prebuilt`](https://github.com/mafintosh/node-sodium-prebuilt) using [`prebuild`](https://github.com/mafintosh/prebuild) rather than more common `node-gyp` or `node-pre-gyp`.

**Comment by mixmix** [comment]
might be worth looking at [pfraze/beaker](https://github.com/beakerbrowser/beaker) ... ii remember something about rebuilding there

**Comment by ahdinosaur** [comment]
@mixmix the relevant line from beaker (changed to `1.4.2`) is:

> npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source

**Comment by ahdinosaur** [comment]
it works! :tada:

**Comment by ungoldman** [comment]
This sound familiar, I think we had similar issues with needing to rebuild leveldb for electron with the [friends](https://github.com/moose-team/friends) project.

**Comment by ungoldman** [comment]
Didn't work for me :(

Failed at this point:

```
> sodium-prebuilt@1.0.22 install /Users/ngoldman/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/sodium-prebuilt
> prebuild --install --preinstall make

./autogen.sh: line 14: aclocal: command not found
make: *** [configure] Error 127
prebuild ERR! build Error: make  failed with exit code 2
prebuild ERR! build     at Object.exports.spawnFailed (/Users/ngoldman/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/prebuild/error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (/Users/ngoldman/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/prebuild/util.js:113:14)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/ngoldman/.nvm/versions/node/v6.7.0/bin/node" "/Users/ngoldman/.nvm/versions/node/v6.7.0/bin/npm" "rebuild" "--runtime=electron" "--target=1.4.2" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! sodium-prebuilt@1.0.22 install: `prebuild --install --preinstall make`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sodium-prebuilt@1.0.22 install script 'prebuild --install --preinstall make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install --preinstall make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium-prebuilt
npm ERR! There is likely additional logging output above.
```

**Comment by ungoldman** [comment]
Build worked after I installed `automake` via homebrew, but running `ferment` produces no results now (no feedback, don't see an electron app starting up either). Hmm..

**Comment by ahdinosaur** [comment]
@ungoldman `npm start`?

**Comment by ungoldman** [comment]
Looks like there was an errant electron process that seemed to be blocking ferment from starting up. Finally got it working!

**Comment by bcomnes** [comment]
Same here.  `Autotools` and `libtool` is required for a source build it seems.

**Comment by mmckegg** [comment]
Thanks @mixmix @ahdinosaur and everyone for getting to the bottom of this!

Just pushed these changes out as v0.0.4 (wow that version is getting super out of control now)

**Comment by Bil0wan** [comment]
I just installed today and I still get the error when trying to launch.
I tried running the fix but it didn't give any output.

**Comment by mmckegg** [comment]
@Bil0wan what operating system are you running?

**Comment by mmckegg** [comment]
Are you **cloning** or are you **installing from npm**?

If from npm have you tried running: `ferment  --rebuild`

Hopefully [this](https://github.com/mafintosh/node-sodium-prebuilt/issues/3) will happen and we won't have to put up with it any more.

**Comment by Bil0wan** [comment]
I am installing through npm.
 Running `ferment --rebuild` gives me this

```
> ferment@0.2.6 rebuild /usr/local/lib/node_modules/ferment
> npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source


> electron-prebuilt@1.4.3 postinstall /usr/local/lib/node_modules/ferment/node_modules/electron-prebuilt
> node install.js


> leveldown@1.4.6 install /usr/local/lib/node_modules/ferment/node_modules/leveldown
> prebuild --install

prebuild ERR! clean error 
prebuild ERR! stack Error: EACCES: permission denied, rmdir 'build'
prebuild ERR! stack     at Error (native)
prebuild ERR! not ok 
prebuild ERR! build Error: EACCES: permission denied, rmdir 'build'
prebuild ERR! build     at Error (native)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild" "--runtime=electron" "--target=1.4.2" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/ferment/npm-debug.log

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ferment@0.2.6 rebuild: `npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ferment@0.2.6 rebuild script 'npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ferment package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ferment
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ferment
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/ferment/npm-debug.log
```

node is 6.7.0
npm is 3.10.3

**Comment by mmckegg** [comment]
@Bil0wan that looks like a permissions error. Maybe try running `sudo ferment --rebuild`?

**Comment by Bil0wan** [comment]
@mmckegg did, it wouldn't even run without it

**Comment by mmckegg** [comment]
@bcomnes hmm, very strange. Something weird with leveldown, your machine and building for electron.

Probably should post an issue on the [leveldown repo](https://github.com/Level/leveldown).

I'll have native installers for Mac and Linux soon. Hopefully that'll get rid of this grief, and we can get back to using software instead of just trying to compile it 😜 .

**Comment by ungoldman** [comment]
@mmckegg I'm guessing `npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source` is running without sudo since it's being invoked by `ferment --rebuild` via a `child_process.spawn` call in [`scripts/start.js`](https://github.com/mmckegg/ferment/blob/0a4d146356d9f4b96a56572bd6f1c85333d3e4cd/scripts/start.js).

@Bil0wan You most likely need to change permissions recursively at the root of your node installation so globally installed node modules don't require sudo.

npm docs recommend fixing permissions for global modules this way:

```
 sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

See [fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) for more info. There are a couple of other suggested fixes there you may want to look at first before trying this one. Ideally you should never need sudo to run npm or node (unless you need to run them in a strict server environment where there's a security concern).

Hope this helps!

**Comment by Bil0wan** [comment]
@ungoldman Thanks a lot, was able to fix it with that information!

**Comment by mixmix** [comment]
You shouldn't need to sudo. If you installed node with nvm, you should be
able to avoid sudo i think
