### ISSUE TITLE
Can't exec "glibtoolize": No such file or directory at 

### ISSUE THREAD

**Issue by balupton** [mmckegg/ferment#17]
$ ferment --rebuild:

```
> prebuild --install --preinstall make

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
Can't exec "glibtoolize": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345, <GEN3> line 5.
autoreconf: failed to run glibtoolize: No such file or directory
autoreconf: glibtoolize is needed because this package uses Libtool
make: *** [configure] Error 1
prebuild ERR! build Error: make  failed with exit code 2
prebuild ERR! build     at Object.exports.spawnFailed (/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/prebuild/error.js:31:10)
prebuild ERR! build     at ChildProcess.<anonymous> (/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/prebuild/util.js:113:14)
prebuild ERR! build     at emitTwo (events.js:106:13)
prebuild ERR! build     at ChildProcess.emit (events.js:191:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.7.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.7.0/bin/npm" "rebuild" "--runtime=electron" "--target=1.4.2" "--disturl=https://atom.io/download/atom-shell" "--build-from-source"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! sodium-prebuilt@1.0.22 install: `prebuild --install --preinstall make`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the sodium-prebuilt@1.0.22 install script 'prebuild --install --preinstall make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sodium-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install --preinstall make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sodium-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sodium-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/npm-debug.log

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/balupton/.nvm/versions/node/v6.7.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.7.0/bin/npm" "run" "rebuild"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ferment@0.2.6 rebuild: `npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ferment@0.2.6 rebuild script 'npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ferment package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ferment
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ferment
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/npm-debug.log
```

/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/balupton/.nvm/versions/node/v6.7.0/bin/node',
1 verbose cli   '/Users/balupton/.nvm/versions/node/v6.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'rebuild' ]
2 info using npm@3.10.3
3 info using node@v6.7.0
4 verbose run-script [ 'prerebuild', 'rebuild', 'postrebuild' ]
5 info lifecycle ferment@0.2.6~prerebuild: ferment@0.2.6
6 silly lifecycle ferment@0.2.6~prerebuild: no script for prerebuild, continuing
7 info lifecycle ferment@0.2.6~rebuild: ferment@0.2.6
8 verbose lifecycle ferment@0.2.6~rebuild: unsafe-perm in lifecycle true
9 verbose lifecycle ferment@0.2.6~rebuild: PATH: /Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment/node_modules/.bin:/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/.bin:/Users/balupton/.nvm/versions/node/v6.7.0/bin:/Users/balupton/.nvm/versions/node/v6.7.0/bin:/Users/balupton/bin:/usr/local/bin:/usr/local/opt/ruby/bin:/Users/balupton/.go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:./node_modules/.bin
10 verbose lifecycle ferment@0.2.6~rebuild: CWD: /Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment
11 silly lifecycle ferment@0.2.6~rebuild: Args: [ '-c',
11 silly lifecycle   'npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source' ]
12 silly lifecycle ferment@0.2.6~rebuild: Returned: code: 1  signal: null
13 info lifecycle ferment@0.2.6~rebuild: Failed to exec rebuild script
14 verbose stack Error: ferment@0.2.6 rebuild: `npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ferment@0.2.6
16 verbose cwd /Users/balupton/.nvm/versions/node/v6.7.0/lib/node_modules/ferment
17 error Darwin 16.0.0
18 error argv "/Users/balupton/.nvm/versions/node/v6.7.0/bin/node" "/Users/balupton/.nvm/versions/node/v6.7.0/bin/npm" "run" "rebuild"
19 error node v6.7.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error ferment@0.2.6 rebuild: `npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source`
22 error Exit status 1
23 error Failed at the ferment@0.2.6 rebuild script 'npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ferment package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm rebuild --runtime=electron --target=1.4.2 --disturl=https://atom.io/download/atom-shell --build-from-source
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ferment
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ferment
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mmckegg** [comment]
Looks like you're running on Mac. I now have a prebuilt version you can install at https://github.com/mmckegg/ferment/releases

But if you want to solve this problem try running:

```bash
$ brew install libtool
```

**Comment by balupton** [comment]
thanks, both of those did the trick, somehow I must have glazed over the mac instructions

**Comment by mmckegg** [comment]
Haha, no I just added them 😄 

You reminded me to do it!

**Comment by Stokestack** [comment]
Why is this necessary when libtool is already on the system? If you have developer tools installed, it's already present at /Library/Developer/CommandLineTools/usr/bin/libtool

But I'm getting the same error compiling a different product.
