### ISSUE TITLE
Windows Builds

### ISSUE THREAD

**Issue by 0x00A** [mmckegg/ferment#40]
Hi! This is a cool project. I also work on a music project that uses electron (https://voltra.co). I'm hanging out with @dominictarr in Amsterdam at the moment and he's saying that you and I are both trying to target windows with level[down]. So I figured I'd see where you where at and if I can help.

I've tried building on macOS and running on an windows 10 IE vm for virtualbox, but when I approach the problem that way, i get something like `%1 is not a valid Win32 application` (pretty much for any native module). I've tried `electron-packager` with something like this...

```
electron-packager . ${PRODUCT} \
  --platform=win32 \
  --arch=x64 \
  --version=${ELECTRON_VERSION:1} \
  --overwrite \
  --icon="${PROJECT}/static/icon.icns" \
  --out=./pkg \
  --ignore="${IGNORE}"
```

I've tried to `npm install -g windows-build-tools` and then build on the virtual machine but im getting some strange network errors from running `node-gyp install 6.9.1 --verbose`...

```
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'install',
gyp verb cli   '6.9.1',
gyp verb cli   '--verbose' ]
gyp info using node-gyp@3.4.0
gyp info using node@6.9.1 | win32 | x64
gyp verb command install [ '6.9.1' ]
gyp verb install input version string "6.9.1"
gyp verb install installing version: 6.9.1
gyp verb ensuring nodedir is created C:\Users\IEUser\.node-gyp\6.9.1
gyp verb created nodedir C:\Users\IEUser\.node-gyp\6.9.1
gyp http GET https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.9.1/node-v6.9.1-headers.tar.gz
gyp verb extracted file from tarball include\node\android-ifaddrs.h
gyp verb extracted file from tarball include\node\ares.h
gyp verb extracted file from tarball include\node\ares_build.h
gyp verb extracted file from tarball include\node\ares_rules.h
gyp verb extracted file from tarball include\node\ares_version.h
gyp verb extracted file from tarball include\node\common.gypi
gyp verb extracted file from tarball include\node\config.gypi
gyp verb extracted file from tarball include\node\nameser.h
gyp verb extracted file from tarball include\node\node.h
gyp verb extracted file from tarball include\node\node_buffer.h
gyp verb extracted file from tarball include\node\node_object_wrap.h
gyp verb extracted file from tarball include\node\node_version.h
gyp verb extracted file from tarball include\node\pthread-barrier.h
gyp verb extracted file from tarball include\node\pthread-fixes.h
gyp verb extracted file from tarball include\node\stdint-msvc2008.h
gyp verb extracted file from tarball include\node\tree.h
gyp verb extracted file from tarball include\node\uv-aix.h
gyp verb extracted file from tarball include\node\uv-bsd.h
gyp verb extracted file from tarball include\node\uv-darwin.h
gyp verb extracted file from tarball include\node\uv-errno.h
gyp verb extracted file from tarball include\node\uv-linux.h
gyp verb extracted file from tarball include\node\uv-sunos.h
gyp verb extracted file from tarball include\node\uv-threadpool.h
gyp verb extracted file from tarball include\node\uv-unix.h
gyp verb extracted file from tarball include\node\uv-version.h
gyp verb extracted file from tarball include\node\uv-win.h
gyp verb extracted file from tarball include\node\uv.h
gyp WARN install got an error, rolling back install
gyp verb command remove [ '6.9.1' ]
gyp verb remove using node-gyp dir: C:\Users\IEUser\.node-gyp
gyp verb remove removing target version: 6.9.1
gyp verb remove removing development files for version: 6.9.1
gyp verb extracted file from tarball include\node\v8-debug.h
gyp ERR! install error
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1026:11)
gyp ERR! stack     at TLSWrap.onread (net.js:569:26)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\IEUser\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "install" "6.9.1" "--verbose"
gyp ERR! cwd C:\work\voltra\node_modules\leveldown
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by 0x00A** [comment]
This turns out to be an issue with `VirtualBox`, certain versions that use a particular network driver was dropping packets, causing node-gyp checksums to fail.
